自定义层
In my opinion ：把net初始化和parameter初始化结合到了一起

In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
print(net)
print(Y.shape)
Y.mean()

Sequential(
  (0): Linear(in_features=8, out_features=128, bias=True)
  (1): CenteredLayer()
)
torch.Size([4, 128])


tensor(-7.4506e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.0973, -1.1857, -0.3494],
        [ 0.2246,  1.3264, -1.5352],
        [-0.0479,  0.3202,  0.7538],
        [ 1.2812, -0.4799,  0.6103],
        [ 0.7843,  0.3899, -0.1560]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[1.6491, 0.2951, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[11.7060],
        [ 9.1581]])