读写文件

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
# it looks like a binary file, and the format of file can be everything
torch.save(x, 'x-file')

In [2]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [3]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [4]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [5]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [6]:
torch.save(net.state_dict(), 'mlp.params')
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.1701, -0.1321, -0.1001,  ..., -0.1763,  0.1074,  0.1441],
                      [-0.0803, -0.0418,  0.1797,  ...,  0.1160, -0.1921,  0.0640],
                      [ 0.0258,  0.0231, -0.0756,  ..., -0.0678,  0.1956, -0.0226],
                      ...,
                      [ 0.0748, -0.1580,  0.1004,  ..., -0.1522,  0.1536, -0.0501],
                      [ 0.1028,  0.2203,  0.0618,  ...,  0.0275,  0.1702,  0.2059],
                      [-0.1963,  0.0675,  0.1607,  ...,  0.1421,  0.0154, -0.0942]])),
             ('hidden.bias',
              tensor([-7.1771e-02,  1.1494e-01, -2.2302e-01,  1.8117e-01, -1.5521e-01,
                      -9.9734e-02,  6.5688e-02,  8.8523e-02,  1.7318e-01,  2.6059e-02,
                       4.6160e-02,  1.7400e-01,  1.6872e-01,  4.9443e-02,  1.6148e-01,
                      -1.3231e-01,  1.5369e-01,  4.6455e-02,  1.0456e-01,  7.2863e-02,
                      -1.4831e-01,  4.8717e-02,  1.3361e-0

In [7]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
# 将clone转变为评估模式
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [8]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])