In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None
print(x.grad)   

None


In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# 反向传播
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [8]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
# 把之前的梯度清零
x.grad.zero_()   
y = x.sum()
y.backward()
x, y, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor(6., grad_fn=<SumBackward0>),
 tensor([1., 1., 1., 1.]))

In [24]:
x.grad.zero_()
y = x * x
# u与y的值相同，但是u不参与计算梯度
u = y.detach()
z = u * x

In [25]:
z.sum().backward()
x.grad == x * x

tensor([True, True, True, True])

In [26]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])